In [1]:
import numpy as np

In [16]:
array_1d =np.array([1,2,3,4,5,6])
array_2d =np.array([[1,2,3],[4,5,6]])
array_3d =np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])

In [5]:
array_1d[0]

1

In [6]:
array_1d[-1]

6

In [7]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_2d[0]

array([1, 2, 3])

In [10]:
array_2d[0,0]

1

In [11]:
array_2d[0,1]

2

In [12]:
array_2d[-1]

array([4, 5, 6])

In [13]:
array_2d[1,-1]

6

In [17]:
array_3d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [18]:
array_3d[0]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
array_3d[0,0,1]

array([4, 5, 6])

In [23]:
array_3d[0,0,0]

array([1, 2, 3])

In [26]:
array_3d[0,0,-1]

array([10, 11, 12])

In [27]:
array_3d[0,0,0,0]

1

In [28]:
array_3d[0,0,0,2]

3

In [29]:
array_3d[0,0,1,2]

6

In [30]:
array_3d[0,0,2,2]

9

In [31]:
array_3d[0,0,3,2]

12

In [32]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [33]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [34]:
array_1d[3:5]

array([4, 5])

In [35]:
array_1d[-3:-1]

array([4, 5])

In [36]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
array_2d[1,1:]

array([5, 6])

In [38]:
array_2d[-2:-2:-1]

array([], shape=(0, 3), dtype=int32)

In [39]:
array_3d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [40]:
array_3d[0,1:,1:]

array([], shape=(0, 3, 3), dtype=int32)