In [1]:
import numpy as np

In [31]:
x =np.array([i for i in range (10)])

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [34]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [35]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [39]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])

In [40]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [41]:
np.amin(arr)

0

In [42]:
np.amin(arr,axis=0)

array([4, 1, 0])

In [43]:
np.amin(arr,axis=1)

array([2, 0, 5])

In [44]:
np.max(arr)

24

In [45]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [46]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

In [47]:
 np.median(arr)

4.0

In [48]:
np.mean(arr)

6.333333333333333

In [49]:
np.std(arr)

6.944222218666553

In [50]:
np.var(arr)

48.22222222222222

In [51]:
np.percentile(arr,50)

4.0

In [53]:
deg =np.array([0,30,45,60,90])

In [54]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [55]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [56]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [57]:
'''arcsin
arccos
arctan
'''

'arcsin\narccos\narctan\n'

In [58]:
arr = np.array([0.1,0.8,-2.2,-9.87])

In [59]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [60]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])

In [27]:
x = np.array([i for i in range (12)])

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
x.resize(2,6)

In [24]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.where(x%2==0,"Good","Bad")

array(['Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Bad'], dtype='<U4')

In [32]:
condlist=[x<5,x>5]
choicelist=[x**2,x**3]

In [34]:
np.select(condlist,choicelist,default=x)

array([   0,    1,    4,    9,   16,    5,  216,  343,  512,  729, 1000,
       1331])