In [4]:
import numpy as np

In [6]:
nump_array = np.array([x for x in range (1,10)])

In [7]:
nump_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
nump_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
boy1 = np.array([x for x in range (1, 13)])

In [16]:
boy1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
boy1.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
boy1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
boy1.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
boy1.reshape(3,2,-1)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
boy1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
gig1 =np.array([i for i in range (1,21)])

In [30]:
gig1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
gig1.reshape(2,10,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]]])

In [37]:
gig1.resize(2,10)

In [39]:
gig1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [47]:
A = [1,2,4,3,5],[8,9,10,11,7]
B = [6,13,15,17,19]

In [48]:
A

([1, 2, 4, 3, 5], [8, 9, 10, 11, 7])

In [49]:
B

[6, 13, 15, 17, 19]

In [54]:
np.add(A,B)

array([[ 7, 15, 19, 20, 24],
       [14, 22, 25, 28, 26]])

In [55]:
np.subtract(B,A)

array([[ 5, 11, 11, 14, 14],
       [-2,  4,  5,  6, 12]])

In [56]:
np.multiply(A,B)

array([[  6,  26,  60,  51,  95],
       [ 48, 117, 150, 187, 133]])

In [59]:
np.divide(A,B)

array([[0.16666667, 0.15384615, 0.26666667, 0.17647059, 0.26315789],
       [1.33333333, 0.69230769, 0.66666667, 0.64705882, 0.36842105]])

In [60]:
np.power(A,2)

array([[  1,   4,  16,   9,  25],
       [ 64,  81, 100, 121,  49]], dtype=int32)

In [62]:
type(A)

tuple

In [63]:
np.power(A,B)

array([[          1,        8192,  1073741824,   129140163,  -463433411],
       [     262144,  -754810903, -1530494976,   -92658101,   442181591]])

In [64]:
np.multiply(A,2)

array([[ 2,  4,  8,  6, 10],
       [16, 18, 20, 22, 14]])