In [1]:
import math

In [6]:
import numpy as np

In [33]:
new_shoes_trials = np.array([[23,15,17,22,74,8,9,76,12],[12,23,98,11,14,87,34,23,98]])

### Ravel add two different list together in python

In [23]:
new_shoes_trials.ravel()

array([23, 15, 17, 22, 74,  8,  9, 76, 12, 12, 23, 98, 11, 14, 87, 34, 23,
       98])

#### Reshape changes or reshape the dataset to the number of rows and column you want but note that the number of rows and column in the dataset has to be counted and specifically said else it would give an error

In [24]:
new_shoes_trials.reshape(3,6)

array([[23, 15, 17, 22, 74,  8],
       [ 9, 76, 12, 12, 23, 98],
       [11, 14, 87, 34, 23, 98]])

#### Resize changes the dataset back to the original row and column when stated

In [30]:
new_shoe_trials.resize(2,9)

In [31]:
new_shoe_trials

array([[list([10, 23, 98, 54, 34, 12, 17, 29, 22, 25]),
        list([32, 65, 76, 54, 24, 56, 78, 48, 87, 23, 43, 54]), 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

#### Split helps to divide dataset

In [35]:
np.hsplit(new_shoe_trials,3)

[array([[list([10, 23, 98, 54, 34, 12, 17, 29, 22, 25]),
         list([32, 65, 76, 54, 24, 56, 78, 48, 87, 23, 43, 54]), 0],
        [0, 0, 0]], dtype=object),
 array([[0, 0, 0],
        [0, 0, 0]], dtype=object),
 array([[0, 0, 0],
        [0, 0, 0]], dtype=object)]

#### Stack add array together with stack function

In [36]:
new_trader_1 = np.array([12,32,27,8,15,8,34,76,20,23])

In [37]:
new_trader_2 = np.array([23,54,65,12,76,44,13,65,17,9])

In [38]:
np.hstack((new_trader_1,new_trader_2))

array([12, 32, 27,  8, 15,  8, 34, 76, 20, 23, 23, 54, 65, 12, 76, 44, 13,
       65, 17,  9])

In [39]:
first_numpy_array = np.array([2,4,7,9])

In [41]:
print (first_numpy_array)

[2 4 7 9]


#### Array with zero

In [46]:
array_with_zero = np.zeros((3,3))

In [47]:
print(array_with_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Array with one

In [48]:
array_with_ones = np.ones((3,3))

In [49]:
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Array with empty

In [50]:
empty_array = np.empty((3,4))

In [51]:
print(empty_array)

[[1.12255944e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.10343781e-312 6.05341455e-066 3.93913018e-062 2.67660320e+184]
 [2.42471327e-052 1.20080344e-071 1.92023367e-052 1.74122781e+184]]


#### Array with arrange method

In [53]:
np_arange = np.arange(12)

In [54]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
np_arange.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
np_arange.resize(2,6)

In [62]:
np_arange

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [64]:
np.hsplit(np_arange,3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

<!-- ## Linespace for linearly equal spaced data element takes 3 argument
# 1 number indicate what the start number will be
# 2 number indicate the end of the array
# 3 or last number shows what the interval will be -->

Linspace for linearly equal space data element
1 number indicate what the start number will be
2 number indicate what the last number will be
3 number indicate the interval of the number

In [74]:
np_linspace = np.linspace(1,6,3)

In [75]:
print(np_linspace)

[1.  3.5 6. ]


In [79]:
oneD_array = np.arange(15)

In [80]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Two Dimensional Array

In [81]:
TwoD_array = oneD_array.reshape(3,5)

In [82]:
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### Three Dimensional Array

In [83]:
ThreeD_array = np.arange(27).reshape(3,3,3)

In [84]:
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
